# Generated by Django 5.2.7 on 2025-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FeatureHighlight",
            new_name="Reason",
        ),
        migrations.RenameField(
            model_name="reason",
            old_name="icon",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="reason",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image illustrating the reason (recommended square ratio).",
                upload_to="reasons/",
            ),
        ),
        migrations.AlterModelOptions(
            name="reason",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Reason",
                "verbose_name_plural": "Reasons",
            },
        ),
    ]
