# Generated by Django 5.2.7 on 2025-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_featurehighlight_to_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reason",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="File name inside public/images/reason (e.g. 'team.png').",
                max_length=200,
            ),
        ),
    ]
