# Generated by Django 5.2.7 on 2025-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_reason_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True)),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of teaching experience."
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="teachers/")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "ordering": ("order", "id"),
            },
        ),
    ]
