# Generated by Django 5.2.7 on 2025-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
