# Generated by Django 5.2.7 on 2025-10-18 14:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_teacher_experience_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicTeacher",
            fields=[],
            options={
                "verbose_name": "Teacher (Public)",
                "verbose_name_plural": "Teachers (Public)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.teacher",),
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Giáo viên",
                "verbose_name_plural": "Giáo viên",
            },
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="role",
        ),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="avatar_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for the avatar (SEO/A11y).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="teacher",
            name="full_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Bật để hiển thị ở trang Home"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại phải gồm 9–15 chữ số, có thể bắt đầu bằng dấu +.",
                        regex="^(?:\\+?84|0)\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="teacher",
            name="specialization",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Chuyên môn"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Đang làm"),
                    ("Inactive", "Nghỉ làm"),
                    ("OnLeave", "Nghỉ phép"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="unpublish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reason",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="File name inside static/public/images/reason (e.g. 'team.png').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="teachers/avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Thứ tự hiển thị ở Home"
            ),
        ),
        migrations.AddIndex(
            model_name="reason",
            index=models.Index(
                fields=["is_active", "order"], name="main_reason_is_acti_5d220f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["status"], name="main_teache_status_b8b93d_idx"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["is_featured", "order"], name="main_teache_is_feat_260479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["publish_at", "unpublish_at"],
                name="main_teache_publish_95bc87_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="uniq_teacher_email_ci",
            ),
        ),
    ]
