# Generated by Django 5.2.7 on 2025-10-18 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_publicteacher_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="So dien thoai phai bat dau bang 0 hoac +84 va gom dung 10 chu so.",
                        regex="^(?:\\+?84|0)\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class. Ví dụ: 'fas fa-comments'.",
                        max_length=80,
                    ),
                ),
                (
                    "duration",
                    models.CharField(help_text="Ví dụ: '3 tháng'.", max_length=50),
                ),
                (
                    "level",
                    models.CharField(help_text="Ví dụ: 'Mọi trình độ'.", max_length=80),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course highlight",
                "verbose_name_plural": "Course highlights",
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="main_course_is_acti_8058b6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("value", models.PositiveIntegerField()),
                ("suffix", models.CharField(blank=True, max_length=10)),
                (
                    "step",
                    models.FloatField(
                        default=1.0, help_text="Increment for counter animation."
                    ),
                ),
                (
                    "delay",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Delay in milliseconds before the animation starts.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site statistic",
                "verbose_name_plural": "Site statistics",
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="main_sitest_is_acti_2a444f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("name", models.CharField(max_length=100)),
                (
                    "initials",
                    models.CharField(
                        help_text="Tối đa 4 ký tự để hiển thị avatar text.",
                        max_length=4,
                    ),
                ),
                ("program", models.CharField(blank=True, max_length=120)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="main_testim_is_acti_30074b_idx",
                    )
                ],
            },
        ),
    ]
