# Generated by Django 5.2.7 on 2025-10-18 16:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_teacher_phone_course_sitestat_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Tiêu đề")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="Phụ đề/ngắn gọn"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả chi tiết"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("award", "Giải thưởng"),
                            ("milestone", "Cột mốc"),
                            ("press", "Báo chí/Truyền thông"),
                            ("certificate", "Chứng nhận"),
                            ("partnership", "Hợp tác"),
                            ("other", "Khác"),
                        ],
                        default="milestone",
                        max_length=20,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lớp Font Awesome, vd: 'fas fa-trophy'.",
                        max_length=80,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Ảnh minh họa (tùy chọn).",
                        null=True,
                        upload_to="achievements/",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text cho ảnh (SEO/A11y).",
                        max_length=150,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Năm đạt thành tựu (tùy chọn).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(3000),
                        ],
                    ),
                ),
                (
                    "metric_value",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Giá trị số (vd: 1000). Bỏ trống nếu không dùng.",
                        null=True,
                    ),
                ),
                (
                    "metric_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Hậu tố hiển thị (vd: '+', 'k', '%').",
                        max_length=10,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="Liên kết ngoài"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Thứ tự hiển thị ở Home"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm đăng"
                    ),
                ),
                (
                    "unpublish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm gỡ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thành tựu",
                "verbose_name_plural": "Thành tựu",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CourseHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class, vd: 'fas fa-comments'",
                        max_length=80,
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        help_text="Chuỗi hiển thị, vd: '3 tháng'", max_length=50
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Thứ tự hiển thị"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course highlight",
                "verbose_name_plural": "Course highlights",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="OutstandingGraduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=120, verbose_name="Tên học viên"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=150, verbose_name="Khóa học"),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày tốt nghiệp"
                    ),
                ),
                (
                    "score_label",
                    models.CharField(
                        blank=True,
                        help_text="Điểm/GPA/Band đạt được (vd: 'IELTS 8.0', 'GPA 3.9/4.0')",
                        max_length=50,
                    ),
                ),
                (
                    "score_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Giá trị số (vd: 8.0). Bỏ trống nếu không dùng.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "score_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Hậu tố (vd: ' / 9', ' điểm')",
                        max_length=10,
                    ),
                ),
                (
                    "testimonial",
                    models.TextField(blank=True, verbose_name="Chia sẻ ngắn"),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="graduates/"),
                ),
                ("photo_alt", models.CharField(blank=True, max_length=150)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Thứ tự hiển thị"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("unpublish_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HV tốt nghiệp xuất sắc",
                "verbose_name_plural": "HV tốt nghiệp xuất sắc",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=100, verbose_name="Tên học viên"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=150, verbose_name="Khóa học"),
                ),
                (
                    "achievement",
                    models.CharField(max_length=150, verbose_name="Thành tựu đạt được"),
                ),
                (
                    "story",
                    models.TextField(verbose_name="Câu chuyện / chia sẻ của học viên"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="success_stories/"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Đã duyệt hiển thị"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Thứ tự hiển thị"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Câu chuyện thành công",
                "verbose_name_plural": "Câu chuyện thành công",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.DeleteModel(
            name="SiteStat",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Khóa học",
                "verbose_name_plural": "Khóa học",
            },
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="main_course_is_acti_8058b6_idx",
        ),
        migrations.RemoveField(
            model_name="course",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="course",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="course",
            name="order",
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Học phí",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("AllLevels", "Mọi trình độ"),
                ],
                default="Beginner",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Tên khóa học"),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["is_active", "order"], name="main_achiev_is_acti_958193_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["publish_at", "unpublish_at"],
                name="main_achiev_publish_5a86f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["kind"], name="main_achiev_kind_1bf86e_idx"),
        ),
        migrations.AddConstraint(
            model_name="achievement",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                condition=models.Q(("is_active", True)),
                name="uniq_achievement_title_active_ci",
            ),
        ),
        migrations.AddField(
            model_name="coursehighlight",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="main.course",
            ),
        ),
        migrations.AddIndex(
            model_name="outstandinggraduate",
            index=models.Index(
                fields=["is_active", "order"], name="main_outsta_is_acti_c18093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outstandinggraduate",
            index=models.Index(
                fields=["publish_at", "unpublish_at"],
                name="main_outsta_publish_c1d0cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coursehighlight",
            index=models.Index(
                fields=["is_active", "order"], name="main_course_is_acti_775454_idx"
            ),
        ),
    ]
