# Generated by Django 5.2.7 on 2025-10-18 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_achievement_coursehighlight_outstandinggraduate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="Global English", max_length=80)),
                (
                    "typed_text",
                    models.CharField(
                        default="Mở ra thế giới với tiếng Anh", max_length=160
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True,
                        default="Lộ trình luyện tập cá nhân hóa, lớp học tương tác và hệ thống theo dõi tiến độ giúp bạn tự tin giao tiếp trong mọi bối cảnh toàn cầu.",
                    ),
                ),
                (
                    "primary_cta_label",
                    models.CharField(default="Liên hệ tư vấn", max_length=80),
                ),
                (
                    "primary_cta_href",
                    models.CharField(default="#advisory", max_length=200),
                ),
                (
                    "secondary_cta_label",
                    models.CharField(
                        blank=True, default="Xem video giới thiệu", max_length=80
                    ),
                ),
                (
                    "secondary_cta_href",
                    models.CharField(
                        blank=True, default="#intro-video", max_length=200
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home setting",
                "verbose_name_plural": "Home settings",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại phải bắt đầu bằng 0 hoặc +84 và gồm đúng 10 chữ số.",
                        regex="^(?:(?:\\+84)|0)\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.CreateModel(
            name="HeroHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class, e.g. 'fas fa-graduation-cap'.",
                        max_length=80,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero highlight",
                "verbose_name_plural": "Hero highlights",
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="main_herohi_is_acti_39842d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "href",
                    models.CharField(
                        blank=True, help_text="Anchor or URL.", max_length=200
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("footer_program", "Footer program"),
                            ("footer_about", "Footer about"),
                        ],
                        default="header",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Navigation link",
                "verbose_name_plural": "Navigation links",
                "ordering": ("location", "order", "id"),
                "indexes": [
                    models.Index(
                        fields=["location", "is_active", "order"],
                        name="main_naviga_locatio_0af01e_idx",
                    )
                ],
            },
        ),
    ]
