# Generated by Django 5.2.7 on 2025-10-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_homesetting_alter_teacher_email_alter_teacher_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="coursehighlight",
            name="icon",
        ),
    ]
