# Generated by Django 5.2.7 on 2025-10-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_achievement_icon_remove_coursehighlight_icon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseHighlight",
        ),
    ]
