# Generated by Django 5.2.7 on 2025-11-02 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_optimize_overview_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bỏ trống nếu học viên thanh toán đúng học phí niêm yết.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Học phí thực thu",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ảnh minh họa tùy chọn.",
                null=True,
                upload_to="achievements/",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="Văn bản thay thế cho ảnh (SEO/A11y).",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="metric_suffix",
            field=models.CharField(
                blank=True,
                help_text="Hậu tố hiển thị (ví dụ: '+', 'k', '%').",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="metric_value",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Giá trị số (ví dụ: 1000). Để trống nếu không dùng.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Thứ tự hiển thị trên trang chủ."
            ),
        ),
    ]
