# Generated by Django 5.2.7 on 2025-11-02 22:48

import django.db.models.deletion
from django.db import migrations, models

STATUS_ENROLLED = "enrolled"
STATUS_COMPLETED = "completed"


def assign_students_forward(apps, schema_editor):
    Student = apps.get_model("main", "Student")
    Course = apps.get_model("main", "Course")
    OutstandingGraduate = apps.get_model("main", "OutstandingGraduate")

    for graduate in OutstandingGraduate.objects.all():
        full_name = getattr(graduate, "student_name", None) or "Học viên"
        defaults = {
            "status": STATUS_COMPLETED,
        }
        if graduate.graduation_date:
            defaults["graduation_date"] = graduate.graduation_date

        student, created = Student.objects.get_or_create(full_name=full_name, defaults=defaults)

        updates = []
        if graduate.graduation_date and not student.graduation_date:
            student.graduation_date = graduate.graduation_date
            updates.append("graduation_date")
        if student.status != STATUS_COMPLETED:
            student.status = STATUS_COMPLETED
            updates.append("status")

        course_title = getattr(graduate, "course_name", "") or ""
        course = None
        if course_title:
            course = Course.objects.filter(title=course_title).first()
            if course and student.primary_course_id is None:
                student.primary_course = course
                updates.append("primary_course")

        if created:
            student.save()
        elif updates:
            student.save(update_fields=updates)

        if course:
            student.courses.add(course)

        graduate.student_id = student.id
        graduate.save(update_fields=["student"])


def assign_students_backward(apps, schema_editor):
    OutstandingGraduate = apps.get_model("main", "OutstandingGraduate")

    for graduate in OutstandingGraduate.objects.all():
        student = getattr(graduate, "student", None)
        if student:
            graduate.student_name = student.full_name
            graduate.save(update_fields=["student_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_course_sale_price_alter_achievement_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="Họ tên")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Số điện thoại")),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="Ngày sinh")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Tiem nang"),
                            (STATUS_ENROLLED, "Dang hoc"),
                            (STATUS_COMPLETED, "Da tot nghiep"),
                            ("paused", "Tam dung"),
                            ("withdrawn", "Da roi"),
                        ],
                        default=STATUS_ENROLLED,
                        max_length=20,
                        verbose_name="Trang thai",
                    ),
                ),
                ("enrollment_date", models.DateField(blank=True, null=True, verbose_name="Ngày nhập học")),
                ("graduation_date", models.DateField(blank=True, null=True, verbose_name="Ngày tốt nghiệp")),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú nội bộ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        to="main.course",
                        verbose_name="Các khóa đang tham gia",
                    ),
                ),
                (
                    "primary_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_students",
                        to="main.course",
                        verbose_name="Khóa học chính",
                    ),
                ),
            ],
            options={
                "ordering": ("full_name", "id"),
                "verbose_name": "Học viên",
                "verbose_name_plural": "Học viên",
            },
        ),
        migrations.AddField(
            model_name="outstandinggraduate",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outstanding_highlights",
                to="main.student",
                verbose_name="Học viên",
            ),
        ),
        migrations.AlterField(
            model_name="outstandinggraduate",
            name="course_name",
            field=models.CharField(
                blank=True,
                help_text="Để trống để dùng khóa học chính của học viên.",
                max_length=150,
                verbose_name="Khóa học hiển thị",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["full_name"], name="main_student_full_name_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="main_student_status_idx"),
        ),
        migrations.RunPython(assign_students_forward, assign_students_backward),
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="student_name",
        ),
        migrations.AlterField(
            model_name="outstandinggraduate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outstanding_highlights",
                to="main.student",
                verbose_name="Học viên",
            ),
        ),
    ]
