# Generated by Django 5.2.7 on 2025-11-03 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_student_model_and_outstandinggraduate_link"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="student",
            new_name="main_studen_full_na_3743b2_idx",
            old_name="main_student_full_name_idx",
        ),
        migrations.RenameIndex(
            model_name="student",
            new_name="main_studen_status_be88c7_idx",
            old_name="main_student_status_idx",
        ),
        migrations.RemoveField(
            model_name="course",
            name="sale_price",
        ),
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="student",
        ),
        migrations.RemoveField(
            model_name="student",
            name="graduation_date",
        ),
        migrations.AddField(
            model_name="outstandinggraduate",
            name="student_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=120,
                verbose_name="Tên học viên",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="outstandinggraduate",
            name="course_name",
            field=models.CharField(max_length=150, verbose_name="Khóa học"),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("enrolled", "Đang học"),
                    ("completed", "Đã tốt nghiệp"),
                    ("paused", "Tạm dừng"),
                    ("withdrawn", "Đã rời"),
                ],
                default="enrolled",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
