# Generated by Django 5.2.7 on 2025-11-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0015_rename_main_student_full_name_idx_main_studen_full_na_3743b2_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuccessStory",
        ),
        migrations.AddField(
            model_name="outstandinggraduate",
            name="achievement",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Thành tựu đạt được"
            ),
        ),
        migrations.AddField(
            model_name="outstandinggraduate",
            name="story",
            field=models.TextField(
                blank=True, verbose_name="Câu chuyện / chia sẻ chi tiết"
            ),
        ),
    ]
