# Generated by Django 5.2.7 on 2025-11-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_delete_successstory_outstandinggraduate_achievement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="testimonial",
        ),
    ]
