# Generated by Django 5.2.7 on 2025-11-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_outstandinggraduate_testimonial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="graduation_date",
        ),
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="score_label",
        ),
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="score_suffix",
        ),
        migrations.RemoveField(
            model_name="outstandinggraduate",
            name="score_value",
        ),
    ]
