# Generated by Django 5.2.7 on 2025-11-03 03:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_outstandinggraduate_course_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Số tiền",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("confirmed", "Đã thu"),
                            ("refunded", "Đã hoàn"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("transfer", "Chuyển khoản"),
                            ("card", "Thẻ"),
                            ("other", "Khác"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Phương thức",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mã giao dịch"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("paid_at", models.DateTimeField(verbose_name="Thời gian thu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="main.course",
                        verbose_name="Khóa học",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="main.student",
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch học phí",
                "verbose_name_plural": "Giao dịch học phí",
                "ordering": ("-paid_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["paid_at"], name="main_studen_paid_at_0be148_idx"
                    ),
                    models.Index(
                        fields=["status", "paid_at"],
                        name="main_studen_status_0dd371_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="main_studen_student_afa03a_idx",
                    ),
                ],
            },
        ),
    ]
