# Generated by Django 5.2.7 on 2025-11-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_studentpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Ngày nhập học"
            ),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="paid_at",
            field=models.DateTimeField(db_index=True, verbose_name="Thời gian thu"),
        ),
    ]
