# Generated by Django 5.2.7 on 2025-11-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_student_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
