# Generated by Django 5.2.7 on 2025-11-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_teacher_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, verbose_name="Địa chỉ"),
        ),
        migrations.AddField(
            model_name="student",
            name="study_program",
            field=models.CharField(
                blank=True,
                choices=[("ielts", "Lộ trình IELTS"), ("toeic", "Lộ trình TOEIC")],
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Chương trình (IELTS/TOEIC)",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("enrolled", "Đang học"),
                    ("completed", "Đã tốt nghiệp"),
                    ("waiting", "Chờ xếp lớp"),
                    ("withdrawn", "Bỏ học"),
                ],
                default="enrolled",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Tiền mặt"),
                    ("transfer", "Chuyển khoản"),
                    ("card", "Thẻ"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Phương thức",
            ),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Chờ xử lý"), ("confirmed", "Đã thu")],
                default="confirmed",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.CreateModel(
            name="StudyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("ielts", "Lộ trình IELTS"),
                            ("toeic", "Lộ trình TOEIC"),
                        ],
                        db_index=True,
                        help_text="IELTS hoặc TOEIC",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ví dụ: Pre-IELTS, IELTS 5.0+, TOEIC 450+, TOEIC 650+",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Mã ngắn: IEL_PRE, IEL_5_0, TOEIC_450...",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("program", "order", "id"),
                "unique_together": {("program", "code")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="study_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="main.studylevel",
                verbose_name="Trình độ (level)",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["study_program"], name="main_studen_study_p_16d5e0_idx"
            ),
        ),
    ]
