# Generated by Django 5.2.7 on 2025-11-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_student_address_student_study_program_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studylevel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studylevel",
            name="cefr",
            field=models.CharField(
                blank=True, help_text="A1, A2, B1, B2, C1, C2...", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="studylevel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studylevel",
            name="max_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Điểm tối đa.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studylevel",
            name="min_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Điểm tối thiểu (IELTS band hoặc điểm TOEIC).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studylevel",
            name="code",
            field=models.CharField(
                help_text="Mã level: IEL_STARTER, TOEIC_INT...",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studylevel",
            name="name",
            field=models.CharField(
                help_text="Tên marketing: IELTS 5.5–6.5 (B2)...", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="studylevel",
            name="program",
            field=models.CharField(
                choices=[("ielts", "Lộ trình IELTS"), ("toeic", "Lộ trình TOEIC")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
